package com.deadlineguard.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity storing contextual recommendations and study plans generated by Gemini AI.
 * Mapped to table `ai_recommendations`.
 * Distinct from the deterministic priority engine.
 */
@Entity
@Table(
    name = "ai_recommendations",
    indexes = {
        @Index(name = "idx_ai_recs_user_date", columnList = "user_id, generated_at"),
        @Index(name = "idx_ai_recs_task", columnList = "task_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"user", "task"})
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class AIRecommendation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    @NotNull(message = "Target student is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = true)
    private Task task;

    @NotBlank(message = "Recommendation type is required")
    @Size(max = 50, message = "Recommendation type must not exceed 50 characters")
    @Column(name = "recommendation_type", nullable = false, length = 50)
    private String recommendationType;

    @NotBlank(message = "Recommendation headline text is required")
    @Column(name = "recommendation_text", nullable = false, columnDefinition = "TEXT")
    private String recommendationText;

    @NotBlank(message = "Contextual AI reasoning is required")
    @Column(name = "ai_reasoning", nullable = false, columnDefinition = "TEXT")
    private String aiReasoning;

    @NotBlank(message = "Suggested action is required")
    @Size(max = 255, message = "Suggested action must not exceed 255 characters")
    @Column(name = "suggested_action", nullable = false, length = 255)
    private String suggestedAction;

    @NotNull(message = "Generation timestamp is required")
    @Column(name = "generated_at", nullable = false)
    @Builder.Default
    private LocalDateTime generatedAt = LocalDateTime.now();
}
